                  - name: Enable Apache modules
                    ansible.builtin.shell:
                      cmd: "a2enmod {{ item }}"
                    loop:
                      - rewrite
                      - proxy
                      - proxy_balancer
                      - proxy_http
                      - headers
                      - lbmethod_bytraffic
                      - lbmethod_byrequests
                    notify: restart apache
                    become: yes)

