---
- name: install apache and git
  become: true
  ansible.builtin.yum:
    name: 
      - "httpd"
      - "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/<your-name>/tooling.git # <-- IMPORTANT: Replace with YOUR GitHub link
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd and enable on boot
  become: true
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: recursively remove temporary directory
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
